### ISSUE TITLE
upload-source-freshness fails to run due to dbt "packages missing"

### ISSUE THREAD

**Issue by martsec** [elementary-data/elementary#1015]
**Describe the bug**
I am running dbt 1.5.3 with elementary 0.9.1 and dbt-elementary 0.9.0

I can run dbt freshness and `dbt run --select elementary --vars "enable_elementary: true" `. without issue. 

However, when I execute `edr run-operation upload-source-freshness --project-dir $(pwd)` it fails the dbt command due to dbt not finding the packages 

```
edr run-operation upload-source-freshness --project-dir $(pwd)
    ________                          __                  
   / ____/ /__  ____ ___  ___  ____  / /_____ ________  __
  / __/ / / _ \/ __ `__ \/ _ \/ __ \/ __/ __ `/ ___/ / / /
 / /___/ /  __/ / / / / /  __/ / / / /_/ /_/ / /  / /_/ / 
/_____/_/\___/_/ /_/ /_/\___/_/ /_/\__/\__,_/_/   \__, /  
                                                 /____/   

Any feedback and suggestions are welcomed! join our community here - https://bit.ly/slack-elementary

2023-07-21 17:28:36 — INFO — Running with edr=0.9.1
Uploading source freshness results |⚠︎                                       | (!) 0/1 [0%] in 1.7s (0.00/s)
Traceback (most recent call last):
  File "/Users//Library/Caches/pypoetry/virtualenvs/dbt--F-KY8c0-py3.10/lib/python3.10/site-packages/elementary/clients/dbt/dbt_runner.py", line 71, in _run_command
    result = subprocess.run(
  File "/Users//.pyenv/versions/3.10.12/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
...
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Compilation Error
  dbt found 2 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.

```

It's odd because i have the packages installed:
```
 dbt deps
15:28:46  Running with dbt=1.5.3
15:28:46  Installing dbt-labs/dbt_utils
15:28:47  Installed from version 1.1.1
15:28:47  Up to date!
15:28:47  Installing elementary-data/elementary
15:28:47  Installed from version 0.9.0
15:28:47  Up to date!
```

**Expected behavior**
Should run with no issues.

**Environment (please complete the following information):**
 - edr Version:0.9.1
 - dbt package Version: 0.9.0
 - dbt 1.5.3

**Additional context**
I've tested with 0.8.2 and it happens the same.

**Comment by Maayan-s** [comment]
Reported by:
https://elementary-community.slack.com/archives/C02CTC89LAX/p1689854444623429
https://elementary-community.slack.com/archives/C02CTC89LAX/p1689954664578269
