### ISSUE TITLE
edr send-report with Slack webhook

### ISSUE THREAD

**Issue by kiasomabes** [elementary-data/elementary#809]
**Is your feature request related to a problem? Please describe.**
`edr send-report` only currently supports `Slack Token`. Since Slack Token needs more access as compared to the Slack Webhook, some security policies may not allow it.

**Describe the solution you'd like**
`edr send-report` to support `Slack Webhook` after report is already generated and uploaded in GCS or S3.

**Describe alternatives you've considered**
As an alternative, perhaps the report which will be generated from `edr send-report` will be uploaded first to GCS or S3, and then still send the report/summary on Slack that is triggered via Slack Webhook. 

**Additional context**

**Would you be willing to contribute this feature?**
Let us know if you're willing to contribute so that we'll be able to provide guidance.

**Comment by elongl** [comment]
Hi @kiasomabes, thanks for opening this issue.
The reason `send-report` doesn't support a Slack webhook is because you cannot send a file over a webhook in Slack.
However, your suggestion of being able to use it to only send the summary makes sense.
Would you be willing to contribute this feature?
I'd be able to provide guidelines if necessary.

**Comment by kiasomabes** [comment]
Hi @elongl sure. Please do provide the guidelines and instructions, I'm not familiar with the codebase myself.

**Comment by noaKurman** [comment]
Hey @kiasomabes! I'll try to help out as much as I can and let me know if you need further help :) 

First of all you can see [here](https://github.com/elementary-data/elementary/blob/e657195474e7badf5f28a97b9dbfcaffd81595a1/elementary/monitor/cli.py#L562) we're checking only if there's a slack token and not for a webhook
Once we pass that get here `data_monitoring_report.py` where we [test to see if we should send the attachment](https://github.com/elementary-data/elementary/blob/e657195474e7badf5f28a97b9dbfcaffd81595a1/elementary/monitor/data_monitoring/report/data_monitoring_report.py#L187), and this is also where we send the summary 
So maybe checking for a webhook in the first location, and setting a var to specify "summary only" and use it in the second location could be a good place to start :)

**Comment by kiasomabes** [comment]
hi @noaKurman thanks for providing the overview! how can I test if my code actually works? i've followed up until the requirements setup using this [guide](https://github.com/elementary-data/elementary/blob/master/CONTRIBUTING.md).

**Comment by noaKurman** [comment]
Hey @kiasomabes! 
To test your code you can just install you own elementary command - 
Just like you usually install elementary CLI using `pip install elementary` you can now install you own code by running `pip install -e path/to/elementary/repo` - and then just run the commands and make sure everything works :)

**Comment by kiasomabes** [comment]
Hi @noaKurman, thanks for the response - I'm encountering some error, which I'm not sure was happening. 

I just tried to run with `edr send-report` for now, to see whether it would actually work as usual. I also modified other files such as the config - but I'm not sure which enforces the parameters to be required in the first place.

```bash
return f(get_current_context(), *args, **kwargs)
TypeError: send_report() missing 1 required positional argument: 'slack_webhook'
``` 

[This is my commit](https://github.com/kiasomabes/elementary/commit/45a33c76cf9fe9c731339aa2c6ca16f360886c4b). Would appreciate feedback, thanks!

**Comment by kiasomabes** [comment]
hi @noaKurman, I'm running into an error upon running `edr send-report --slack-webhook <webhook-url>`. The error is
`raise DbtCommandError(err, command_args, err_msg)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.`

My changes are in this [fork](https://github.com/elementary-data/elementary/compare/master...kiasomabes:elementary:send-report-slack-webhook). Would appreciate feedback. Thank you!

**Comment by noaKurman** [comment]
Hey @kiasomabes 
Can you send the full error? Doesn't look like you changed anything in the data so I'm not sure if this error is related to the changes you made or something is just wrong with the envirnonment you set up

**Comment by IDoneShaveIt** [comment]
Hey @kiasomabes!
I was looking at the [fork](https://github.com/elementary-data/elementary/compare/master...kiasomabes:elementary:send-report-slack-webhook) you shared with us, and I have another idea on how to implement it there 🙂

I think that adding an `--slack-webhook` option to the cli send-report command is good, but instead of adding the `summary_only` option to the send report command, you should:
1. Instead of passing `summary_only` param to `send_report` method you should use the CLI argument `--disable` like `edr send report --slack-webhook <webhook> --disable html_attachment`.
2. Replace the `NotImlementedError` on the `send_report` method at the `SlackWebhookClient` with an indicative error that explains that "Slack is not support sending files using webhooks, please use slack token instead". 

That way we keep the DataMonitoringReport class a bit simpler, and we get the same effect 🙂

**Comment by kiasomabes** [comment]
> Hey @kiasomabes Can you send the full error? Doesn't look like you changed anything in the data so I'm not sure if this error is related to the changes you made or something is just wrong with the environment you set up

I think it has something to do with the dbt setup - not sure if it's related to some other issue with [dbt](https://github.com/dbt-labs/dbt-core/issues/7659). 

`2023-05-23 16:25:16 — INFO — Running with edr=0.7.9
2023-05-23 16:25:16 — INFO — Downloading edr internal dbt package
2023-05-23 16:25:22 — ERROR — Unable to get the latest invocation: Failed to run dbt command.
2023-05-23 16:25:22 — INFO — Downloading edr internal dbt package
2023-05-23 16:25:22 — INFO — Running dbt deps --project-dir /Users/kia.somabes/Desktop/elementary/elementary/monitor/dbt_project
Usage: dbt deps [OPTIONS]
Try 'dbt deps -h' for help.

Error: Invalid value for '--profiles-dir': Path '/Users/kia.somabes/.dbt' does not exist.
Traceback (most recent call last):
  File "/Users/kia.somabes/Desktop/elementary/elementary/clients/dbt/dbt_runner.py", line 65, in _run_command
    result = subprocess.run(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', 'deps', '--project-dir', '/Users/kia.somabes/Desktop/elementary/elementary/monitor/dbt_project']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kia.somabes/Desktop/elementary/venv/bin/edr", line 33, in <module>
    sys.exit(load_entry_point('elementary-data', 'console_scripts', 'edr')())
  File "/Users/kia.somabes/Desktop/elementary/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kia.somabes/Desktop/elementary/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/kia.somabes/Desktop/elementary/elementary/cli/cli.py", line 67, in invoke
    return super().invoke(ctx)
  File "/Users/kia.somabes/Desktop/elementary/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kia.somabes/Desktop/elementary/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kia.somabes/Desktop/elementary/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kia.somabes/Desktop/elementary/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kia.somabes/Desktop/elementary/elementary/monitor/cli.py", line 579, in send_report
    data_monitoring = DataMonitoringReport(
  File "/Users/kia.somabes/Desktop/elementary/elementary/monitor/data_monitoring/report/data_monitoring_report.py", line 37, in __init__
    super().__init__(
  File "/Users/kia.somabes/Desktop/elementary/elementary/monitor/data_monitoring/data_monitoring.py", line 49, in __init__
    self._download_dbt_package_if_needed(force_update_dbt_package)
  File "/Users/kia.somabes/Desktop/elementary/elementary/monitor/data_monitoring/data_monitoring.py", line 91, in _download_dbt_package_if_needed
    package_downloaded = self.internal_dbt_runner.deps()
  File "/Users/kia.somabes/Desktop/elementary/elementary/clients/dbt/dbt_runner.py", line 102, in deps
    success, _ = self._run_command(command_args=["deps"], quiet=quiet)
  File "/Users/kia.somabes/Desktop/elementary/elementary/clients/dbt/dbt_runner.py", line 87, in _run_command
    raise DbtCommandError(err, command_args, err_msg)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.`

When I tried `pip list | grep dbt`, I got the following:
`dbt-core                 1.5.0
dbt-extractor            0.4.1
`

**Comment by IDoneShaveIt** [comment]
Hey @kiasomabes thanks for continue and working on this contribution!
When you run `edr send-report` elementary try and generate the report based on your dbt project (using the elementary profile that you provide).
The inner dbt project, is used to connect to the DWH (with elementary profile) and create the report from elementary artifacts (created with elementary dbt package).

So the error that you see means that elementary couldn't generate a report, and therefore you couldn't test the webhook.
Do you have a dbt project that you used to run with elementary? If so you could use it to test the feature, and if you don't have we could help you with the tests as well 🙂
